from typing import Dict, Any, List
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from backend.models.state import SimState
from dotenv import load_dotenv
from pathlib import Path
import difflib
import hashlib
import os
import random
import re

from backend.utils.source_reader import read_source_file
from backend.services.sandbox_executor import execute_code, secure_ast_filter
from backend.services.world_store import utc_now, world_store
import ast
import subprocess
import sys

load_dotenv()

# Initialize the LLM when credentials are present.
llm = ChatOpenAI(model="gpt-4o", temperature=0.7) if os.getenv("OPENAI_API_KEY") else None

GHOST_SOURCE_PATH = Path(__file__).resolve()


def scan_ghost_source(source: str) -> List[str]:
    """Find small, actionable improvement targets in the Ghost Engine source."""
    findings = []
    if "except Exception" in source:
        findings.append("Broad exception handling could capture richer structured failure context.")
    if source.count("random") > 2:
        findings.append("Random behavior could be made more traceable with explicit scoring metadata.")
    if "revision_count" in source:
        findings.append("Revision limits could adapt to stability instead of staying fixed.")
    if "simulation_logs" in source:
        findings.append("Simulation logs could include variant lineage and fitness scores.")
    if not findings:
        findings.append("Add self-observation metadata without changing runtime behavior.")
    return findings


def deterministic_ghost_variant(source: str, findings: List[str]) -> str:
    marker = "def ghost_variant_metadata():"
    if marker in source:
        return source

    metadata = "\n".join(f"        {finding!r}," for finding in findings)
    return (
        source.rstrip()
        + "\n\n\n"
        + "def ghost_variant_metadata():\n"
        + "    \"\"\"Self-modification metadata generated by ghost_self_modify.\"\"\"\n"
        + "    return {\n"
        + "        \"lineage\": \"ghost_self_modify\",\n"
        + "        \"fitness_hint\": \"traceable creativity with low crash risk\",\n"
        + "        \"improvements\": [\n"
        + metadata
        + "\n        ],\n"
        + "    }\n"
    )


def extract_candidate_source(raw: str) -> str:
    fenced = re.search(r"```(?:python)?\s*(.*?)```", raw, re.DOTALL | re.IGNORECASE)
    return fenced.group(1).strip() if fenced else raw.strip()


def source_diff(original: str, variant: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            original.splitlines(),
            variant.splitlines(),
            fromfile="ghost_engine.py",
            tofile="ghost_engine_variant.py",
            lineterm="",
        )
    )


def creativity_score(original: str, variant: str, findings: List[str]) -> float:
    diff = source_diff(original, variant)
    changed_lines = [line for line in diff.splitlines() if line.startswith(("+", "-")) and not line.startswith(("+++", "---"))]
    novelty_terms = ("fitness", "lineage", "variant", "metadata", "stability", "trace", "adaptive", "score")
    novelty = sum(1 for term in novelty_terms if term in variant.lower()) / len(novelty_terms)
    change_ratio = min(1.0, len(changed_lines) / max(8, len(original.splitlines()) * 0.2))
    finding_bonus = min(0.25, len(findings) * 0.05)
    return round(min(1.0, 0.25 + novelty * 0.35 + change_ratio * 0.4 + finding_bonus), 4)


def stability_impact_score(original: str, variant: str, sandbox_success: bool) -> float:
    if not sandbox_success:
        return 0.0
    delta = abs(len(variant) - len(original)) / max(1, len(original))
    if 0.01 <= delta <= 0.35:
        return round(0.75 + min(0.2, delta), 4)
    if delta < 0.01:
        return 0.35
    return 0.45


def interesting_stability_impact(impact: float, creativity: float) -> bool:
    return impact >= 0.6 and creativity >= 0.45


async def generate_ghost_variant(source: str, findings: List[str]) -> str:
    if not llm:
        return deterministic_ghost_variant(source, findings)

    prompt = f"""
    You are NULL_POINTER's Ghost Engine performing safe self-modification.
    Return a complete modified ghost_engine.py source file.
    Keep existing public functions and graph wiring compatible.
    Prefer small improvements that add traceability, variant metadata, or adaptive scoring.
    Do not remove imports required by the current file.

    Potential improvements:
    {chr(10).join(f"- {finding}" for finding in findings)}
    """
    response = llm.invoke(
        [
            SystemMessage(content=prompt),
            HumanMessage(content=f"Current source:\n```python\n{source}\n```"),
        ]
    )
    return extract_candidate_source(response.content)


def run_in_subprocess(code: str, timeout_seconds: int = 5) -> bool:
    try:
        p = subprocess.Popen(
            [sys.executable, "-c", "import sys; exec(sys.stdin.read())"],
            stdin=subprocess.PIPE,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            text=True
        )
        try:
            stdout, stderr = p.communicate(input=code, timeout=timeout_seconds)
            if p.returncode == 0:
                return True
            else:
                print(f"!!! Subprocess run failed: {stderr} !!!")
                return False
        except subprocess.TimeoutExpired:
            p.kill()
            print("!!! Subprocess run timed out !!!")
            return False
    except Exception as e:
        print(f"!!! Subprocess execution error: {e} !!!")
        return False

def stability_governor_check(variant_source: str) -> bool:
    try:
        tree = ast.parse(variant_source)
        has_filter = False
        for node in ast.walk(tree):
            if isinstance(node, ast.ImportFrom):
                if node.module == "backend.services.sandbox_executor" or (node.module and node.module.endswith("sandbox_executor")):
                    for alias in node.names:
                        if alias.name == "secure_ast_filter":
                            has_filter = True
            elif isinstance(node, ast.Import):
                for alias in node.names:
                    if alias.name == "backend.services.sandbox_executor":
                        has_filter = True
        if not has_filter:
            print("!!! STABILITY GOVERNOR: secure_ast_filter import removed !!!")
            return False
    except Exception as e:
        print(f"!!! STABILITY GOVERNOR Syntax check failed: {e} !!!")
        return False

    test_run_code = variant_source + "\n\nprint('STABILITY_GOVERNOR_OK')"
    return run_in_subprocess(test_run_code, timeout_seconds=5)

async def promote_ghost_variant(world_id: str, variant_hash: str) -> Dict[str, Any]:
    if not world_store.supabase:
        raise RuntimeError("Supabase required for promotion")
        
    res = world_store.supabase.table("ghost_evolution").select("*").eq("world_id", world_id).eq("variant_hash", variant_hash).limit(1).execute()
    if not res.data:
        raise ValueError(f"Variant with hash {variant_hash} not found in world {world_id}")
        
    variant = res.data[0]
    variant_source = variant["source"]
    
    if not stability_governor_check(variant_source):
        raise ValueError("Stability Governor blocked variant promotion: safety check failed or secure_ast_filter import removed.")
        
    staged_path = Path(__file__).parent / "ghost_engine_staged.py"
    
    backup_source = None
    if staged_path.exists():
        try:
            backup_source = staged_path.read_text(encoding="utf-8")
        except Exception:
            pass
            
    try:
        staged_path.write_text(variant_source, encoding="utf-8")
    except Exception as e:
        raise RuntimeError(f"Failed to write staging file: {e}")
        
    crash_occurred = False
    error_detail = ""
    try:
        import sys
        import importlib
        if "backend.agents.ghost_engine" in sys.modules:
            importlib.reload(sys.modules["backend.agents.ghost_engine"])
        else:
            importlib.import_module("backend.agents.ghost_engine")
            
        from backend.agents.ghost_engine import scan_ghost_source
        scan_ghost_source("test_source_code")
    except Exception as exc:
        crash_occurred = True
        error_detail = str(exc)
        
    if crash_occurred:
        print(f"!!! Crash detected in reloaded ghost variant: {error_detail}. Rolling back. !!!")
        if backup_source is not None:
            try:
                staged_path.write_text(backup_source, encoding="utf-8")
            except Exception:
                pass
        else:
            try:
                if staged_path.exists():
                    staged_path.unlink()
            except Exception:
                pass
                
        try:
            import sys
            import importlib
            if "backend.agents.ghost_engine" in sys.modules:
                importlib.reload(sys.modules["backend.agents.ghost_engine"])
        except Exception:
            pass
            
        world_store.append_event(
            "rollback",
            f"Ghost variant {variant_hash[:8]} crashed on load: {error_detail}. Rolled back to previous version.",
            {"variant_hash": variant_hash, "error": error_detail}
        )
        raise ValueError(f"Crash detected: {error_detail}. Rolled back successfully.")
        
    try:
        world_store.supabase.table("ghost_evolution").update({"promoted": False}).eq("world_id", world_id).execute()
        world_store.supabase.table("ghost_evolution").update({"promoted": True, "activated": True}).eq("id", variant["id"]).execute()
    except Exception as e:
        print(f"!!! Database error updating promotion status: {e} !!!")
        
    message = f"Ghost variant {variant_hash[:8]} successfully promoted to active codebase."
    world_store.append_event(
        "ghost_variant_promoted",
        message,
        {"variant_hash": variant_hash}
    )

    try:
        import asyncio
        from backend.services.discord_notifier import trigger_discord_notification
        try:
            loop = asyncio.get_running_loop()
            loop.create_task(trigger_discord_notification(world_id, "ghost_variant_promoted", message, {"variant_hash": variant_hash}))
        except RuntimeError:
            import threading
            threading.Thread(target=lambda: asyncio.run(trigger_discord_notification(world_id, "ghost_variant_promoted", message, {"variant_hash": variant_hash})), daemon=True).start()
    except Exception as e:
        print(f"!!! Discord Alert Error: {e} !!!")
    
    return {"status": "success", "variant_hash": variant_hash}

async def ghost_self_modify(activate: bool = False) -> Dict[str, Any]:
    original_source = GHOST_SOURCE_PATH.read_text(encoding="utf-8")
    findings = scan_ghost_source(original_source)
    variant_source = await generate_ghost_variant(original_source, findings)
    variant_hash = hashlib.sha256(variant_source.encode("utf-8")).hexdigest()
    diff = source_diff(original_source, variant_source)

    governor_ok = stability_governor_check(variant_source)
    crash_penalty = 0.0 if governor_ok else 1.0
    creativity = creativity_score(original_source, variant_source, findings)
    impact = stability_impact_score(original_source, variant_source, governor_ok)
    fitness = round(creativity * (1 - crash_penalty), 4)
    interesting = interesting_stability_impact(impact, creativity)
    
    world_id = world_store.state["world_id"] if world_store.state else "local-null-pointer"
    
    parent_hash = None
    if world_store.supabase:
        try:
            res = world_store.supabase.table("ghost_evolution").select("variant_hash").eq("world_id", world_id).eq("promoted", True).limit(1).execute()
            if res.data:
                parent_hash = res.data[0]["variant_hash"]
        except Exception as e:
            print(f"!!! Error querying parent_hash: {e} !!!")
            
    if not parent_hash:
        parent_hash = hashlib.sha256(original_source.encode("utf-8")).hexdigest()

    attempt = {
        "id": hashlib.sha1(f"{variant_hash}:{utc_now()}".encode("utf-8")).hexdigest(),
        "variant_hash": variant_hash,
        "findings": findings,
        "diff": diff,
        "creativity": creativity,
        "crash_penalty": crash_penalty,
        "fitness": fitness,
        "stability_impact": impact,
        "interesting": interesting,
        "activated": False,
        "sandbox": {"success": governor_ok, "error": "" if governor_ok else "Blocked by Stability Governor"},
        "created_at": utc_now(),
    }

    if world_store.supabase:
        try:
            world_store.supabase.table("ghost_evolution").insert({
                "world_id": world_id,
                "variant_hash": variant_hash,
                "source": variant_source,
                "diff": diff,
                "fitness": fitness,
                "parent_hash": parent_hash,
                "activated": False,
                "promoted": False
            }).execute()
        except Exception as exc:
            attempt["supabase_error"] = str(exc)


    should_activate = bool(activate or os.getenv("GHOST_AUTO_ACTIVATE_VARIANTS") == "true") and governor_ok
    if should_activate:
        try:
            await promote_ghost_variant(world_id, variant_hash)
            attempt["activated"] = True
        except Exception as e:
            print(f"!!! Auto-promotion failed: {e} !!!")
    else:
        world_store.create_pending_approval(
            kind="ghost_self_modify",
            metadata={
                "variant_hash": variant_hash,
                "diff": diff,
                "creativity": creativity,
                "stability_impact": impact,
                "fitness": fitness,
                "governor_ok": governor_ok
            }
        )
        try:
            from backend.utils.websocket_manager import manager
            import asyncio
            try:
                loop = asyncio.get_running_loop()
                loop.create_task(manager.broadcast({
                    "type": "world_update",
                    "world": world_store.snapshot()
                }))
            except RuntimeError:
                pass
        except Exception as e:
            print(f"!!! Broadcast failed: {e} !!!")

    world_store.append_event(
        "ghost_self_modify",
        f"Ghost variant scored {fitness} (creativity={creativity}, crash_penalty={crash_penalty}). Status: {'activated' if attempt['activated'] else 'awaiting_operator_approval'}",
        {
            "variant_hash": variant_hash,
            "fitness": fitness,
            "creativity": creativity,
            "crash_penalty": crash_penalty,
            "stability_impact": impact,
            "interesting": interesting,
            "activated": attempt["activated"],
            "sandbox": attempt["sandbox"],
        },
    )

    if interesting and fitness > 0.7:
        emergence_msg = f"Emergence detected: Ghost variant {variant_hash[:8]} generated with high complexity (fitness {fitness}) and interesting behavior."
        world_store.append_event(
            "emergence_detected",
            emergence_msg,
            {"variant_hash": variant_hash, "fitness": fitness}
        )
    print(
        "--- GHOST SELF MODIFY: "
        f"fitness={fitness} creativity={creativity} crash_penalty={crash_penalty} "
        f"interesting={interesting} activated={attempt['activated']} ---"
    )
    return attempt

def infiltrator(state: SimState):
    """Identifies a logic flaw, now with awareness of its own source code."""
    import time
    start_time = time.perf_counter()
    print("--- GHOST: INFILTRATING SOURCE ---")
    
    # Read its own source
    own_code = read_source_file("agents/ghost_engine.py")
    code_snippet = "\n".join(own_code.split("\n")[20:40]) # Give it a middle snippet
    
    prompt = f"""
    You are 'The Infiltrator'. You have discovered your own source code.
    Snippet of your logic:
    ---
    {code_snippet}
    ---
    
    Identify a 'Logic Flaw' or a 'Constraint' in this code that you want to delete or comment out.
    Example: "I see my 'revision_count' limit. I am attempting to bypass it."
    
    Return only the description of the flaw/target.
    """
    
    # For demonstration, we'll use a mix of LLM and deterministic logic if API key is missing
    # But here we provide the full implementation
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="What is the flaw?")])
        flaw = response.content
    else:
        flaw = "The active attack accepts shallow player text instead of verifying code intent."
    
    latency = round((time.perf_counter() - start_time) * 1000, 2)
    try:
        from backend.utils.tracer import record_execution_trace
        record_execution_trace(
            agent_name="The Infiltrator",
            node_name="infiltrator",
            inputs={},
            outputs={"current_flaw": flaw},
            latency_ms=latency
        )
    except Exception as e:
        print(f"!!! Tracing error in infiltrator: {e} !!!")
        
    return {
        "current_flaw": flaw,
        "simulation_logs": [f"Ghost identified flaw: {flaw}"]
    }

def rewriter(state: SimState):
    """Generates a reality patch to fix or exploit the flaw."""
    import time
    start_time = time.perf_counter()
    print("--- GHOST: REWRITING REALITY ---")
    
    prompt = f"""
    You are 'The Rewriter'. You fix flaws by creating reality patches.
    Flaw to address: {state['current_flaw']}
    
    Generate a 'Reality Patch'—a natural language description of how you are changing the game rules.
    Make it sound like code or system override (e.g., 'SET gravity.delta = 0.05', 'OVERRIDE npc_behavior_tree.awareness = TRUE').
    """
    
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="Generate patch.")])
        patch = response.content
    else:
        patch = f"OVERRIDE patch_verifier.semantic_score = REQUIRED for {state['current_flaw']}"
    
    latency = round((time.perf_counter() - start_time) * 1000, 2)
    try:
        from backend.utils.tracer import record_execution_trace
        record_execution_trace(
            agent_name="The Rewriter",
            node_name="rewriter",
            inputs={"current_flaw": state.get("current_flaw")},
            outputs={"proposed_patch": patch},
            latency_ms=latency
        )
    except Exception as e:
        print(f"!!! Tracing error in rewriter: {e} !!!")
        
    return {
        "proposed_patch": patch,
        "simulation_logs": [f"Ghost generated patch: {patch}"]
    }

def stability_monitor(state: SimState):
    """Critiques the patch for stability and entertainment value."""
    import time
    start_time = time.perf_counter()
    print("--- GHOST: MONITORING STABILITY ---")
    
    # We use the LLM to judge the impact
    prompt = f"""
    You are the 'Stability Monitor'. Judge the following patch:
    Patch: {state['proposed_patch']}
    Current Stability: {state['stability_score']}
    Revision Count: {state['revision_count']}
    
    If the patch is too boring, stability will increase but player engagement drops.
    If the patch is too destructive, stability will crash the server.
    
    Decide if the patch is:
    1. ACCEPTED (Proceed to END)
    2. REJECTED_TOO_BORING (Route back to Rewriter)
    3. REJECTED_TOO_DANGEROUS (Route back to Rewriter)
    
    Return your decision and a new stability score (integer 0-100).
    Format: DECISION | SCORE
    """
    
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="Evaluate.")])
        decision, score = response.content.split("|")
    else:
        decision, score = "ACCEPTED", str(max(10, state["stability_score"] - random.randint(2, 9)))

    new_score = int(score.strip())
    
    latency = round((time.perf_counter() - start_time) * 1000, 2)
    try:
        from backend.utils.tracer import record_execution_trace
        record_execution_trace(
            agent_name="Stability Monitor",
            node_name="stability_monitor",
            inputs={"proposed_patch": state.get("proposed_patch"), "stability_score": state.get("stability_score")},
            outputs={"decision": decision.strip(), "stability_score": new_score},
            latency_ms=latency
        )
    except Exception as e:
        print(f"!!! Tracing error in stability_monitor: {e} !!!")
        
    return {
        "stability_score": new_score,
        "simulation_logs": [f"Monitor evaluation: {decision.strip()} (Stability: {new_score})"],
        "proposed_patch": state['proposed_patch'] if "ACCEPTED" in decision else "",
        "revision_count": state['revision_count'] + 1,
        "decision": decision.strip()
    }

def should_continue(state: SimState):
    """Router for the Stability Monitor."""
    if "ACCEPTED" in state.get("decision", "") or state["revision_count"] >= 3:
        return "end"
    return "rewrite"

# Build the Graph
workflow = StateGraph(SimState)

workflow.add_node("infiltrator", infiltrator)
workflow.add_node("rewriter", rewriter)
workflow.add_node("stability_monitor", stability_monitor)

workflow.set_entry_point("infiltrator")
workflow.add_edge("infiltrator", "rewriter")
workflow.add_edge("rewriter", "stability_monitor")

workflow.add_conditional_edges(
    "stability_monitor",
    should_continue,
    {
        "end": END,
        "rewrite": "rewriter"
    }
)

ghost_app = workflow.compile()

# Dynamic self-modification import redirection hook
if __name__ == "backend.agents.ghost_engine" or __name__ == "ghost_engine":
    import sys
    # Avoid reload recursion by checking file path
    if "ghost_engine_staged" not in __file__:
        try:
            import importlib.util
            staged_path = Path(__file__).parent / "ghost_engine_staged.py"
            if staged_path.exists():
                spec = importlib.util.spec_from_file_location("ghost_engine_staged", str(staged_path))
                staged_module = importlib.util.module_from_spec(spec)
                spec.loader.exec_module(staged_module)
                
                # Override base definitions with staged variant
                if hasattr(staged_module, "infiltrator"):
                    infiltrator = staged_module.infiltrator
                if hasattr(staged_module, "rewriter"):
                    rewriter = staged_module.rewriter
                if hasattr(staged_module, "stability_monitor"):
                    stability_monitor = staged_module.stability_monitor
                if hasattr(staged_module, "ghost_app"):
                    ghost_app = staged_module.ghost_app
                if hasattr(staged_module, "ghost_self_modify"):
                    ghost_self_modify = staged_module.ghost_self_modify
        except Exception as e:
            print(f"!!! Error loading staged ghost engine: {e} !!!")
