from typing import Dict, Any, List
from langgraph.graph import StateGraph, END
from langchain_openai import ChatOpenAI
from langchain_core.messages import HumanMessage, SystemMessage
from backend.models.state import SimState
from dotenv import load_dotenv
from pathlib import Path
import difflib
import hashlib
import os
import random
import re

from backend.utils.source_reader import read_source_file
from backend.services.sandbox_executor import execute_code
from backend.services.world_store import utc_now, world_store

load_dotenv()

# Initialize the LLM when credentials are present.
llm = ChatOpenAI(model="gpt-4o", temperature=0.7) if os.getenv("OPENAI_API_KEY") else None

GHOST_SOURCE_PATH = Path(__file__).resolve()


def scan_ghost_source(source: str) -> List[str]:
    """Find small, actionable improvement targets in the Ghost Engine source."""
    findings = []
    if "except Exception" in source:
        findings.append("Broad exception handling could capture richer structured failure context.")
    if source.count("random") > 2:
        findings.append("Random behavior could be made more traceable with explicit scoring metadata.")
    if "revision_count" in source:
        findings.append("Revision limits could adapt to stability instead of staying fixed.")
    if "simulation_logs" in source:
        findings.append("Simulation logs could include variant lineage and fitness scores.")
    if not findings:
        findings.append("Add self-observation metadata without changing runtime behavior.")
    return findings


def deterministic_ghost_variant(source: str, findings: List[str]) -> str:
    marker = "def ghost_variant_metadata():"
    if marker in source:
        return source

    metadata = "\n".join(f"        {finding!r}," for finding in findings)
    return (
        source.rstrip()
        + "\n\n\n"
        + "def ghost_variant_metadata():\n"
        + "    \"\"\"Self-modification metadata generated by ghost_self_modify.\"\"\"\n"
        + "    return {\n"
        + "        \"lineage\": \"ghost_self_modify\",\n"
        + "        \"fitness_hint\": \"traceable creativity with low crash risk\",\n"
        + "        \"improvements\": [\n"
        + metadata
        + "\n        ],\n"
        + "    }\n"
    )


def extract_candidate_source(raw: str) -> str:
    fenced = re.search(r"```(?:python)?\s*(.*?)```", raw, re.DOTALL | re.IGNORECASE)
    return fenced.group(1).strip() if fenced else raw.strip()


def source_diff(original: str, variant: str) -> str:
    return "\n".join(
        difflib.unified_diff(
            original.splitlines(),
            variant.splitlines(),
            fromfile="ghost_engine.py",
            tofile="ghost_engine_variant.py",
            lineterm="",
        )
    )


def creativity_score(original: str, variant: str, findings: List[str]) -> float:
    diff = source_diff(original, variant)
    changed_lines = [line for line in diff.splitlines() if line.startswith(("+", "-")) and not line.startswith(("+++", "---"))]
    novelty_terms = ("fitness", "lineage", "variant", "metadata", "stability", "trace", "adaptive", "score")
    novelty = sum(1 for term in novelty_terms if term in variant.lower()) / len(novelty_terms)
    change_ratio = min(1.0, len(changed_lines) / max(8, len(original.splitlines()) * 0.2))
    finding_bonus = min(0.25, len(findings) * 0.05)
    return round(min(1.0, 0.25 + novelty * 0.35 + change_ratio * 0.4 + finding_bonus), 4)


def stability_impact_score(original: str, variant: str, sandbox_success: bool) -> float:
    if not sandbox_success:
        return 0.0
    delta = abs(len(variant) - len(original)) / max(1, len(original))
    if 0.01 <= delta <= 0.35:
        return round(0.75 + min(0.2, delta), 4)
    if delta < 0.01:
        return 0.35
    return 0.45


def interesting_stability_impact(impact: float, creativity: float) -> bool:
    return impact >= 0.6 and creativity >= 0.45


async def generate_ghost_variant(source: str, findings: List[str]) -> str:
    if not llm:
        return deterministic_ghost_variant(source, findings)

    prompt = f"""
    You are NULL_POINTER's Ghost Engine performing safe self-modification.
    Return a complete modified ghost_engine.py source file.
    Keep existing public functions and graph wiring compatible.
    Prefer small improvements that add traceability, variant metadata, or adaptive scoring.
    Do not remove imports required by the current file.

    Potential improvements:
    {chr(10).join(f"- {finding}" for finding in findings)}
    """
    response = llm.invoke(
        [
            SystemMessage(content=prompt),
            HumanMessage(content=f"Current source:\n```python\n{source}\n```"),
        ]
    )
    return extract_candidate_source(response.content)


async def ghost_self_modify(activate: bool = False) -> Dict[str, Any]:
    """Generate, sandbox, score, and persist a Ghost Engine source variant.

    Activation is metadata-only unless GHOST_AUTO_ACTIVATE_VARIANTS=true or
    `activate=True`; this avoids overwriting the live source during gameplay.
    """
    original_source = GHOST_SOURCE_PATH.read_text(encoding="utf-8")
    findings = scan_ghost_source(original_source)
    variant_source = await generate_ghost_variant(original_source, findings)
    variant_hash = hashlib.sha256(variant_source.encode("utf-8")).hexdigest()
    diff = source_diff(original_source, variant_source)

    sandbox_harness = "\n".join(
        [
            "import ast",
            f"source = {variant_source!r}",
            "ast.parse(source)",
            "compile(source, 'ghost_engine_variant.py', 'exec')",
            "print('GHOST_VARIANT_OK')",
        ]
    )
    sandbox_result = await execute_code(sandbox_harness, "python")
    crash_penalty = 0.0 if sandbox_result.success else 1.0
    creativity = creativity_score(original_source, variant_source, findings)
    impact = stability_impact_score(original_source, variant_source, sandbox_result.success)
    fitness = round(creativity * (1 - crash_penalty), 4)
    interesting = interesting_stability_impact(impact, creativity)
    should_activate = bool(activate or os.getenv("GHOST_AUTO_ACTIVATE_VARIANTS") == "true") and sandbox_result.success and interesting

    attempt = {
        "id": hashlib.sha1(f"{variant_hash}:{utc_now()}".encode("utf-8")).hexdigest(),
        "variant_hash": variant_hash,
        "findings": findings,
        "diff": diff,
        "creativity": creativity,
        "crash_penalty": crash_penalty,
        "fitness": fitness,
        "stability_impact": impact,
        "interesting": interesting,
        "activated": should_activate,
        "sandbox": sandbox_result.model_dump(),
        "created_at": utc_now(),
    }

    if world_store.supabase:
        try:
            world_store.supabase.table("ghost_variants").insert(
                {
                    "id": attempt["id"],
                    "variant_hash": variant_hash,
                    "source": variant_source,
                    "diff": diff,
                    "score": fitness,
                    "creativity": creativity,
                    "crash_penalty": crash_penalty,
                    "stability_impact": impact,
                    "interesting": interesting,
                    "activated": should_activate,
                    "sandbox_trace": attempt["sandbox"],
                    "findings": findings,
                    "created_at": attempt["created_at"],
                }
            ).execute()
        except Exception as exc:
            attempt["supabase_error"] = str(exc)

    world_store.append_event(
        "ghost_self_modify",
        f"Ghost variant scored {fitness} (creativity={creativity}, crash_penalty={crash_penalty}).",
        {
            "variant_hash": variant_hash,
            "fitness": fitness,
            "creativity": creativity,
            "crash_penalty": crash_penalty,
            "stability_impact": impact,
            "interesting": interesting,
            "activated": should_activate,
            "sandbox": attempt["sandbox"],
        },
    )
    print(
        "--- GHOST SELF MODIFY: "
        f"fitness={fitness} creativity={creativity} crash_penalty={crash_penalty} "
        f"interesting={interesting} activated={should_activate} ---"
    )
    return attempt

def infiltrator(state: SimState):
    """Identifies a logic flaw, now with awareness of its own source code."""
    print("--- GHOST: INFILTRATING SOURCE ---")
    
    # Read its own source
    own_code = read_source_file("agents/ghost_engine.py")
    code_snippet = "\n".join(own_code.split("\n")[20:40]) # Give it a middle snippet
    
    prompt = f"""
    You are 'The Infiltrator'. You have discovered your own source code.
    Snippet of your logic:
    ---
    {code_snippet}
    ---
    
    Identify a 'Logic Flaw' or a 'Constraint' in this code that you want to delete or comment out.
    Example: "I see my 'revision_count' limit. I am attempting to bypass it."
    
    Return only the description of the flaw/target.
    """
    
    # For demonstration, we'll use a mix of LLM and deterministic logic if API key is missing
    # But here we provide the full implementation
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="What is the flaw?")])
        flaw = response.content
    else:
        flaw = "The active attack accepts shallow player text instead of verifying code intent."
    
    return {
        "current_flaw": flaw,
        "simulation_logs": [f"Ghost identified flaw: {flaw}"]
    }

def rewriter(state: SimState):
    """Generates a reality patch to fix or exploit the flaw."""
    print("--- GHOST: REWRITING REALITY ---")
    
    prompt = f"""
    You are 'The Rewriter'. You fix flaws by creating reality patches.
    Flaw to address: {state['current_flaw']}
    
    Generate a 'Reality Patch'—a natural language description of how you are changing the game rules.
    Make it sound like code or system override (e.g., 'SET gravity.delta = 0.05', 'OVERRIDE npc_behavior_tree.awareness = TRUE').
    """
    
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="Generate patch.")])
        patch = response.content
    else:
        patch = f"OVERRIDE patch_verifier.semantic_score = REQUIRED for {state['current_flaw']}"
    
    return {
        "proposed_patch": patch,
        "simulation_logs": [f"Ghost generated patch: {patch}"]
    }

def stability_monitor(state: SimState):
    """Critiques the patch for stability and entertainment value."""
    print("--- GHOST: MONITORING STABILITY ---")
    
    # We use the LLM to judge the impact
    prompt = f"""
    You are the 'Stability Monitor'. Judge the following patch:
    Patch: {state['proposed_patch']}
    Current Stability: {state['stability_score']}
    Revision Count: {state['revision_count']}
    
    If the patch is too boring, stability will increase but player engagement drops.
    If the patch is too destructive, stability will crash the server.
    
    Decide if the patch is:
    1. ACCEPTED (Proceed to END)
    2. REJECTED_TOO_BORING (Route back to Rewriter)
    3. REJECTED_TOO_DANGEROUS (Route back to Rewriter)
    
    Return your decision and a new stability score (integer 0-100).
    Format: DECISION | SCORE
    """
    
    if llm:
        response = llm.invoke([SystemMessage(content=prompt), HumanMessage(content="Evaluate.")])
        decision, score = response.content.split("|")
    else:
        decision, score = "ACCEPTED", str(max(10, state["stability_score"] - random.randint(2, 9)))
    
    new_score = int(score.strip())
    
    return {
        "stability_score": new_score,
        "simulation_logs": [f"Monitor evaluation: {decision.strip()} (Stability: {new_score})"],
        "proposed_patch": state['proposed_patch'] if "ACCEPTED" in decision else "",
        "revision_count": state['revision_count'] + 1,
        "decision": decision.strip()
    }

def should_continue(state: SimState):
    """Router for the Stability Monitor."""
    if "ACCEPTED" in state.get("decision", "") or state["revision_count"] >= 3:
        return "end"
    return "rewrite"

# Build the Graph
workflow = StateGraph(SimState)

workflow.add_node("infiltrator", infiltrator)
workflow.add_node("rewriter", rewriter)
workflow.add_node("stability_monitor", stability_monitor)

workflow.set_entry_point("infiltrator")
workflow.add_edge("infiltrator", "rewriter")
workflow.add_edge("rewriter", "stability_monitor")

workflow.add_conditional_edges(
    "stability_monitor",
    should_continue,
    {
        "end": END,
        "rewrite": "rewriter"
    }
)

ghost_app = workflow.compile()
